### ISSUE TITLE
Missing icon for stop spotify listening

### ISSUE THREAD

**Issue by rom4ukqq** [TakosThings/Fluent-Discord#104]
![Screenshot 2022-03-27 213525](https://user-images.githubusercontent.com/45468764/160295712-aa7338ee-96d4-448f-b325-b3207b8e8cd3.png)
![Screenshot 2022-03-27 213643](https://user-images.githubusercontent.com/45468764/160295714-a250b7a4-cb92-476a-a91e-ff765a8a1da8.png)

**Comment by TakosThings** [comment]
Try adding this to your CSS file to see if it fixes it
```CSS
html[lang^=en-].theme-dark .panels-3wFtMD .button-12Fmur[aria-label=Stop]::before {
  content: "\e15b";
}
```
