### ISSUE TITLE
Support for MicaForEveryone/Transparency

### ISSUE THREAD

**Issue by Matrakalero** [TakosThings/Fluent-Discord#271]
Tried to make "--fluent-acrylic-background" rgba but it doesn't work

Other themes have this feature and you can use [MFE](https://github.com/MicaForEveryone/MicaForEveryone) to blur the background like in [this theme](https://github.com/MeowIce/TranslucencePlus) for example:

![image](https://github.com/TakosThings/Fluent-Discord/assets/102875439/aea61534-c5e7-4eb8-81fb-3a01307994fe)

It would be nice to get transparent support in this theme

**Comment by DAPOTTIS** [comment]
I'd like to have support for this as well, tried modifying the CSS myself but I couldnt figure it out (I dont have any experience with css)
just needs a transparent background and MFE (or KDE force blur for linux) will blur it.

**Comment by TakosThings** [comment]
> Tried to make "--fluent-acrylic-background" rgba but it doesn't work

There's a few layers with solid backgrounds under the bg layer, they would all need to be set to `transparent` for this to work correctly. 

As for adding this as a base feature - there are a few reasons for why this hasn't been added:
* Electron transparency option breaks window snapping - This should be basic functionality for any software since Windows 7.
* MFE requires .NET 3.1 which is EOL and now unsupported which could pose a security risk.

**Comment by celunah** [comment]
> Tried to make "--fluent-acrylic-background" rgba but it doesn't work
> 
> Other themes have this feature and you can use [MFE](https://github.com/MicaForEveryone/MicaForEveryone) to blur the background like in [this theme](https://github.com/MeowIce/TranslucencePlus) for example:
> 
> ![image](https://private-user-images.githubusercontent.com/102875439/294718803-aea61534-c5e7-4eb8-81fb-3a01307994fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0ODM0MzksIm5iZiI6MTcwNzQ4MzEzOSwicGF0aCI6Ii8xMDI4NzU0MzkvMjk0NzE4ODAzLWFlYTYxNTM0LWM1ZTctNGViOC04MWZiLTNhMDEzMDc5OTRmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQxMjUyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODFmNjE4NjkyYjdkNTI2MTQ2M2U1MjliYTY1NmQxMGE1ZGFjMjU2NmVjZjcwYjQ1ZGE0MTM4NWViZThhNGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b7ZQS3pF15Eg1CfJPRBJlwEI3h6UtN62W0e1Mbu7qsg)
> 
> It would be nice to get transparent support in this theme

i managed to enable transparency support, use this css:
```css
/* curved corners + transparency (use MFE, extremely mild blur effect) */
:root {
  --fluent-acrylic-background: rgba(0, 0, 0, .05);
}

body, .app_de4237, .app_b1f720, .notAppAsidePanel__9d124, .appAsidePanelWrapper__714a6 {
  background: rgba(0, 0, 0, .05);
}

#app-mount {
  border-radius: 8px;
  background: rgba(0, 0, 0, .5);
}
```
this will make all elements behind fluent-discord's background transparent, enabling mica effects to work on discord, it will be very mild though.

mfe settings required are as follows:
![image](https://github.com/TakosThings/Fluent-Discord/assets/71488561/e36c9383-be3d-40d2-8ba3-515cd7ba9587)

**Comment by Matrakalero** [comment]
That works, looks great, thank u this should be marked as solved
![image](https://github.com/TakosThings/Fluent-Discord/assets/102875439/9c260f0a-7c0e-47ad-82bd-c3c9438e2235)

**Comment by ShayBox** [comment]
> ```css
> /* curved corners + transparency (use MFE, extremely mild blur effect) */
> :root {
>   --fluent-acrylic-background: rgba(0, 0, 0, .05);
> }
> 
> body, .app_de4237, .app_b1f720, .notAppAsidePanel__9d124, .appAsidePanelWrapper__714a6 {
>   background: rgba(0, 0, 0, .05);
> }
> 
> #app-mount {
>   border-radius: 8px;
>   background: rgba(0, 0, 0, .5);
> }
> ```

It somewhat works but not as it appears in the picture, I believe an update has added more layers to disable.

It would be nice to get support for this officially, especially since Vencord/Vesktop and others have supported transparency without MicaForEveryone for a long time.

The only downside appears to be the loss of resizing because of an electron change, which also effects every other modern electron app with transparency such as VSCode, and I'm willing to deal with it since I use AltSnap anyway.

**Comment by celunah** [comment]
So looks like I'm gonna have to check all the layers behind the app and disable them again lol, that's Discord

**Comment by Undisputed00x** [comment]
Uhm has anyone any update on how to get a translucent background with this theme ?
 Personally have replace all `background: .*` with `transparent` values and still no change

**EDIT**: found these classes make **Fluent-Discord theme** transparent.
```scss
body, #app-mount,
.typeWindows_a934d8,
.app_a01fb1,.bg_d4b6c5,
.guilds_a4d4d9,.scroller_fea3ef,
.bg_d4b6c5::before,
.container_cbd271,
.chatContent_a7d72e,
.layer_d4b6c5 .contentRegion_c25c6d,
.nowPlayingColumn_c2739c .container_bf550a,
.container_c2739c .tabBody_c2739c  {
        background: transparent !important;
}
```

**Comment by Dreaming-Codes** [comment]
Update transparent custom css
```css
/* curved corners + transparency (use MFE, extremely mild blur effect) */
:root {
  --fluent-acrylic-background: rgba(0, 0, 0, 0);
}

.bg__960e4 {
  display: none;
}

body, #app-mount,
.typeWindows__421ed,
.app__160d8,.bg__960e4,
.guilds_c48ade,.scroller_ef3116,
.bg__960e4::before,
.container_c8ffbb,
.chatContent_f75fb0,
.layer__960e4 .contentRegion__23e6b,
.nowPlayingColumn__133bf .container__7d20c,
.container__133bf .tabBody__133bf  {
        background: transparent !important;
}

#app-mount {
  border-radius: 8px;
  background: rgba(0, 0, 0, .5);
}

```
