### ISSUE TITLE
Broken button and icons are gone.

### ISSUE THREAD

**Issue by ghost** [TakosThings/Fluent-Discord#282]
![image](https://github.com/TakosThings/Fluent-Discord/assets/150472922/71ea14d6-7499-4ce3-b7a2-7f00c30da4e6)
![image](https://github.com/TakosThings/Fluent-Discord/assets/150472922/32cfaa21-b76f-4a4e-b09c-a86e7965a99c)

**Comment by ghost** [comment]
Version 1.10.3

**Comment by TakosThings** [comment]
Krisp icon is a known issue but it's unfixable.

Missing icon fixed in #280

**Comment by ghost** [comment]
@TakosThings Why it unfixable? (Just intresting)

**Comment by TakosThings** [comment]
Icon replacements are done by matching the `aria-label` on buttons, etc. For the Krisp button it looks like this:
```SCSS
    &[aria-label="Noise Suppression powered by Krisp" i]::before{
        content: "\F61F"; // NoiseCancellation
    }
```
(this is also why the icons only work with English)
For whatever reason the `aria-label` is removed entirely when the Krisp popout is open. I checked the history of Metro for Discord and it's been an issue for at least [4 years](https://github.com/TakosThings/Metro-for-Discord/blame/64114ff10a6118d3e2cba1177dc208c268b535d9/CHANGELOG.md#L349)
