### ISSUE TITLE
Won't show Vencord plugin context menu item icons

### ISSUE THREAD

**Issue by keplerHaloxx** [TakosThings/Fluent-Discord#289]
On hover or right click on a message, the items that were added by a Vencord plugin doesn't have icons

https://github.com/TakosThings/Fluent-Discord/assets/80098945/3adc747b-24d2-46dc-a9b8-6a5935391411

**Comment by GalaxinTM** [comment]
I found a fix for this with Vencord's QuickCSS. I recommend using FontForge or similar to find the characters you need from the font this theme uses
Here's what I put:
```css
html[lang^=en-].theme-dark .wrapper_ef319f .button_ef319f[aria-label="Hide Attachments"]::before {
  content: "\ed1a";
}
html[lang^=en-].theme-dark .wrapper_ef319f .button_ef319f[aria-label="Show Attachments"]::before {
  content: "\f78d";
}

html[lang^=en-].theme-dark .wrapper_ef319f .button_ef319f[aria-label="View Raw (Left Click) / Copy Raw (Right Click)"]::before {
  content: "\e943";
}

html[lang^=en-].theme-dark .wrapper_ef319f .button_ef319f[aria-label="Translate"]::before {
  content: "\e8c1";
}
```
