### ISSUE TITLE
Channels & Roles and Members Tab not affected by the Theme

### ISSUE THREAD

**Issue by sluhtie** [TakosThings/Fluent-Discord#295]
**Bug description**
The Members Page such as the Channels & Roles Page, is not affected by the Theme's Background.

**Screenshots**
<img width="1624" alt="Bildschirmfoto 2024-06-13 um 14 24 20" src="https://github.com/TakosThings/Fluent-Discord/assets/97464371/ab5504ce-14f3-4e09-a7a9-fcd77bcddc05">
<img width="1624" alt="Bildschirmfoto 2024-06-13 um 14 24 46" src="https://github.com/TakosThings/Fluent-Discord/assets/97464371/e3605d33-0f96-40a8-9dd9-67b00d85318f">

**Comment by celunah** [comment]
# Solution
Here is a temporary fix for this issue until @TakosThings fixes it.

```css
.chat_a7d72e,
.header_d20375,
.mainTableContainer_e23072,
.container_f1fd9c,
.header_f1fd9c {
    background: transparent !important;
}

.mainTableContainer_e23072 {
    border-radius: 0;
}
```

![image](https://github.com/user-attachments/assets/7bcef201-4c0f-4d09-94b5-1925b0369d2b)
![image](https://github.com/user-attachments/assets/477807cc-c4c2-4cf6-be70-c09f1cfb82ea)
