### ISSUE TITLE
Change icons in left menu of emoji picker

### ISSUE THREAD

**Issue by GalaxinTM** [TakosThings/Fluent-Discord#304]
**Is your feature request related to a problem? Please describe.**
Sort of. There is a missing icon, and the favorites icon (star) is in the wrong place (image 1)

**Describe the solution you'd like**
The top emojis should be a trophy, or an icon to resemble trending
The favorite emojis should be a star
Both shown in image 2

Here's a quick and easy solution to it to be put in Vencord's QuickCSS
```css
.theme-dark .categoryItemDefaultCategory_dfa278.categoryItem_dfa278[aria-label=favorites]::before {
  content: "\e1ce";
}

.theme-dark .categoryItemDefaultCategory_dfa278.categoryItem_dfa278[aria-label="top guild emoji"]::before {
    content: "\ecad";
}
```

**Additional context**
Image 1
![image](https://github.com/user-attachments/assets/6f7e43ec-cad1-4596-b163-344f85a22e2a)
Image 2
![image](https://github.com/user-attachments/assets/f90c49ad-aff5-4fcc-8c9c-2d269a203b05)
