### ISSUE TITLE
Glow Effect On Titles

### ISSUE THREAD

**Issue by rom4ukqq** [TakosThings/Fluent-Discord#76]
It's hard to read text because of this effect, what about the user option for this?
v0.0.14
![Screenshot 2022-03-09 165432](https://user-images.githubusercontent.com/45468764/157456148-1c1ec2ff-d909-45da-9875-b5b675d7acb4.png)
v.1.0.0
![Screenshot 2022-03-09 165448](https://user-images.githubusercontent.com/45468764/157456179-d0711a9a-cfde-4202-8237-7af87a1d7d74.png)

**Comment by TakosThings** [comment]
This is actually poor font rendering. I'll look at importing the semibold variant as well or changing back to Segoe variable.

Temporary fix if you're using the static theme is to remove the below (should be lines 39 -42) (Windows 10/11 only)
```CSS
@font-face {
  font-family: "Segoe UI";
  src: local("Segoe UI"), url("https://takosthings.github.io/Fluent-Discord-Fonts/segoeui.ttf") format("truetype");
}
```
